In [58]:
import scipy.stats as stats

In [59]:
import seaborn as sns
import pandas as pd
import numpy as np
dataset=pd.read_csv("output.csv")

In [60]:
dataset.head()

id        date      open      high       low     close  shares_traded  \
0   1  2023-01-02  18131.70  18215.15  18086.50  18197.45    256073979.0   
1   2  2023-01-03  18163.20  18251.95  18149.80  18232.55    208699772.0   
2   3  2023-01-04  18230.65  18243.00  18020.60  18042.95    235162202.0   
3   4  2023-01-05  18101.95  18120.30  17892.60  17992.15    269949738.0   
4   5  2023-01-06  18008.05  18047.40  17795.55  17859.45    238220578.0   

   turnover  
0  11793.06  
1  13680.91  
2  16687.71  
3  22108.53  
4  17495.25

In [61]:
dataset_table=pd.crosstab(dataset['low'],dataset['open'])
print(dataset_table)

open      16977.30  16984.30  16994.65  17031.75  17060.40  17066.60  \
low                                                                    
16828.35         0         0         0         0         0        15   
16850.15         0         0        15         0         0         0   
16913.75         0         0         0        15         0         0   
16917.35         0         0         0         0         0         0   
16918.55         0        15         0         0         0         0   
...            ...       ...       ...       ...       ...       ...   
19758.40         0         0         0         0         0         0   
19865.35         0         0         0         0         0         0   
19914.65         0         0         0         0         0         0   
19944.10         0         0         0         0         0         0   
20043.45         0         0         0         0         0         0   

open      17076.20  17097.40  17111.80  17160.55  ...  19784.00

In [72]:
observed_values=dataset_table.values
print(observed_values)

[[ 0  0  0 ...  0  0  0]
 [ 0  0 15 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0 15  0]
 [ 0  0  0 ... 15  0  0]
 [ 0  0  0 ...  0  0 15]]


In [63]:
val=stats.chi2_contingency(dataset_table)

In [64]:
val

Chi2ContingencyResult(statistic=456750.00000000023, pvalue=0.0, dof=30276, expected_freq=array([[0.08571429, 0.08571429, 0.08571429, ..., 0.08571429, 0.08571429,
        0.08571429],
       [0.08571429, 0.08571429, 0.08571429, ..., 0.08571429, 0.08571429,
        0.08571429],
       [0.08571429, 0.08571429, 0.08571429, ..., 0.08571429, 0.08571429,
        0.08571429],
       ...,
       [0.08571429, 0.08571429, 0.08571429, ..., 0.08571429, 0.08571429,
        0.08571429],
       [0.08571429, 0.08571429, 0.08571429, ..., 0.08571429, 0.08571429,
        0.08571429],
       [0.08571429, 0.08571429, 0.08571429, ..., 0.08571429, 0.08571429,
        0.08571429]]))

In [65]:
expected_values=val[3]


In [66]:
no_of_rows=len(dataset_table.iloc[0:2,0:2])
no_of_columns=len(dataset_table.iloc[0:2,0:2])
ddof=(no_of_rows-1)*(no_of_columns-1)
print("Degree of freedom:",ddof)
alpha=0.05

Degree of freedom: 1


In [67]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(observed_values,expected_values)])
chi_square_statistic=chi_square[0]+chi_square[1]

In [68]:
print(chi_square_statistic)

5220.00000000004


In [69]:
critical_value=chi2.ppf(q=1-alpha,df=ddof)
print(critical_value)

3.841458820694124


In [70]:
p_value=1-chi2.cdf(x=chi_square_statistic,df=ddof)
print("p_value:",p_value)
print("Significance level: ",alpha)
print("Degree of Freedom: ",ddof)
print("p-value: ",p_value)



p_value: 0.0
Significance level:  0.05
Degree of Freedom:  1
p-value:  0.0


In [73]:
if chi_square_statistic>=critical_value:
    print("Reject H0,There is a relationship between the number of shares traded and turnover")
else:
    print("Retain H0,There is no relationship between the number of shares traded and turnover")
if p_value<=alpha:
    print("Reject H0,There is a relationship between the number of shares traded and turnover")
else:
    print("Retain H0,There is no relationship between the number of shares traded")

Reject H0,There is a relationship between the number of shares traded and turnover
Reject H0,There is a relationship between the number of shares traded and turnover
